### PR TITLE
Update deps for Dependabot Alerts

### PR DESCRIPTION
**Pull request by aj-stein-nist**

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
OK, the [`engines` constraint and new `overrides` feature of npm's `package.json` specification new in 8.3.x. and newer](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) is going to save us here. I was able to clear these deps and build locally. We do need to upgrade our NodeJS version (the default version of `npm` shipping with Node 16.x is unfortunately older and I want clean, reliable GHA runs without updating npm in the runner shennanigans, Node 18.x seems to be reliable). This is the smallest and easiest change to get us where we need to be.

@JustKuzya, the interfaces generate with no discernible change in output and the generate schema step runs as is. Testing the app locally to ensure it works as planned. Let me know if we can hop on a call to discuss tomorrow.

**Review by JustKuzya — APPROVED** [review]
I have no objections to the version bumps and the type script I understand. :)

**Comment by aj-stein-nist** [comment]
Per discussion with @JustKuzya yesterday, this is good to go but he would like us to wait and merge for some substantial changes to test this after they are rolled in.

**Comment by david-waltermire-nist** [comment]
@JustKuzya and @aj-stein-nist How (and when) should we address the check annotation on the files tab? There are some good code cleanup suggestions there.

**Comment by JustKuzya** [comment]
Whenever you and AJ have time to walk through it - today or Monday.
DC

**Comment by aj-stein-nist** [comment]
> @JustKuzya and @aj-stein-nist How (and when) should we address the check annotation on the files tab? There are some good code cleanup suggestions there.

I had wanted to hold off on that until we were further along, per https://github.com/usnistgov/oscal-cat/issues/50. See issue and comment in GitHub build workflow in GHA that it will eventually not to be gated.

https://github.com/usnistgov/oscal-cat/blob/abb442c5fb917f1003e313633a3610a027cf1139/.github/workflows/build.yml#L52-L53

I will look for some time to meet on Monday!

**Comment by aj-stein-nist** [comment]
Per request today from Dave and Dmitry: retest on current develop commit and verify before merge.

**Pull request merged**
